export const products = [
  {
    id: 1,
    name: 'American Classic',
    label: 'Prueba la',
    ingredients: [
      '150gr de res',
      'Pepinillos',
      'Doble tocineta',
      'Queso Americano  ',
      'lechuga',
      'tomate',
      'cebolla',
      'Salsas',
    ],
    description: 'A classic American burger with lettuce, tomato, and cheese.',
    price: 10,
    image: './images/products/american_classic.webp',
  },
  {
    id: 2,
    name: 'Coronel Crispy',
    label: 'Te presentamos la',
    ingredients: [
      '200gr de pollo crispy',
      'tocineta',
      'cebolla empanizada',
      'Queso americano',
      'Vegetales',
      'Salsas',
    ],
    description: 'A classic American burger with lettuce, tomato, and cheese.',
    price: 13,
    image: './images/products/coronel_crispy.webp',
  },

  {
    id: 3,
    name: 'Frito Cheese',
    label: 'Descubre la',
    ingredients: [
      '150gr de res',
      'Queso mozzarella empanizado',
      'Jamon ahumado',
      'Tocineta',
      'Vegetales',
      'Salsas',
    ],
    description:
      'Hamburguesa con crujiente queso frito y un toque picante ideal para amantes del queso.',
    price: 11,
    image: './images/products/frito_cheese.webp',
  },
  {
    id: 4,
    name: 'Afrodita',
    label: 'No te pierdas la',
    ingredients: [
      'Hamburguesa de pescado',
      'Camarones crispy',
      'Aderezo de pimentón ahumado',
      'Lechuga',
      'Cebolla empanizada',
    ],
    description:
      'Unión divina de carne jugosa con queso azul y cebolla caramelizada, para paladares exigentes.',
    price: 13,
    image: './images/products/afrodita.webp',
  },
  {
    id: 5,
    name: 'Street Burguer',
    label: 'Vive la',
    ingredients: [
      '150gr de res o pollo a la plancha',
      'Queso de mano',
      'Papitas',
      'Lechuga',
      'Tomate',
      'Cebolla',
      'Salsas en pan frito',
    ],
    description:
      'Auténtico sabor callejero con doble carne, queso derretido y cebolla crujiente.',
    price: 10,
    image: './images/products/street_burguer.webp',
  },
  {
    id: 7,
    name: 'Crispy Teriyaki',
    label: 'Experimenta la',
    ingredients: [
      '150gr de Pollo Crispy',
      'Tocineta',
      'Cebolla Teriyaki',
      'Mostaza',
      'Mayo',
      'Lechuga',
    ],
    description:
      'Fusión asiática con pollo crujiente bañado en teriyaki y piña caramelizada.',
    price: 10,
    image: './images/products/crispy_teriyaki.webp',
  },
  {
    id: 8,
    name: 'Tequeburguer',
    label: 'Prueba la',
    ingredients: [
      '150gr de Res o Pollo',
      'Platano frito',
      'Tocineta',
      'Lechuga',
      'Salsas de la casa en tapas de tequeño',
    ],
    description: 'Explosión de sabores mexicanos con toque de tequila premium',
    price: 11,
    image: './images/products/tequeburguer.jpg',
  },
  {
    id: 9,
    name: 'Pizza Burguer',
    label: 'Te presentamos la',
    ingredients: [
      '150gr de res o pollo',
      'Tocineta',
      'Maiz dulce',
      'Salsas',
      'Tapa superior de pizza (Vegetales, Pestocineta, Margarita, 4 quesos)',
    ],
    description: 'Fusión italiana con los mejores ingredientes de pizza',
    price: 12.5,
    image: './images/products/pizza_burguer.jpg',
  },
  {
    id: 10,
    name: 'Pueblerina',
    label: 'Descubre la',
    ingredients: [
      '150gr de res',
      'Queso de cabra',
      'Tocineta',
      'Maiz dulce',
      'Vegetales',
      'Salsas',
    ],
    description: 'Auténtico sabor campestre con ingredientes tradicionales',
    price: 9,
    image: './images/products/pueblerina.jpg',
  },
  {
    id: 11,
    name: 'Burgués BBQ',
    label: 'No te pierdas la',
    ingredients: [
      '150gr de res',
      'Chuleta ahumada',
      'Tocineta',
      'Cebolla empanizada',
      'BBQ',
      'Lechuga',
      'Tomate',
      'Salsa de la casa',
    ],
    description: 'Clásico sabor barbecue con ahumado natural',
    price: 12,
    image: './images/products/chicken_bbq1.jpg',
  },
  {
    id: 12,
    name: 'Cinta Blue',
    label: 'Vive la',
    ingredients: [
      'Cordon Blue (Pollo frito relleno de jamon, queso paisa y queso crema)',
      'Salsa de la casa',
      'Vegetales en Cesar',
    ],
    description: 'Armonía de sabores gourmet con queso azul y frutos',
    price: 13,
    image: './images/products/cinta_blue.jpg',
  },
  {
    id: 13,
    name: 'Chicken Barbecue',
    label: 'Auténtica',
    ingredients: [
      '150gr de pollo crispy bañado en salsa bbq',
      'Pepinillos',
      'Tocineta',
      'Lechuga',
      'Tomate',
      'Cebolla',
      'Salsas',
    ],
    description: 'Combinación jugosa de pollo y sabores ahumados',
    price: 10.5,
    image: './images/products/chicken_bbq.jpg',
  },
  {
    id: 14,
    name: 'Aristócrata',
    label: 'Experimenta la',
    ingredients: [
      'Pechuga de pollo a la plancha',
      'Tocineta crujiente',
      'Queso americano',
      'Lechuga',
      'Tomate',
      'Cebolla',
      'Salsas',
    ],
    description: 'Experiencia gourmet con ingredientes de lujo',
    price: 9,
    image: './images/products/classic.jpg',
  },
  {
    id: 15,
    name: 'Classic',
    label: 'Prueba la',
    ingredients: [
      '150gr de res',
      'Tocineta',
      'Queso americano',
      'Lechuga',
      'Tomate',
      'Cebolla',
      'Mostaza',
      'Ketchup',
      'Salsa de la casa',
    ],
    description: 'Versión esencial de la hamburguesa clásica',
    price: 8.5,
    image: './images/products/classic.jpg',
  },
  {
    id: 16,
    name: 'Burgues Doble',
    label: 'Te presentamos la',
    ingredients: [
      '2 carnes de res (120gr c/u)',
      'Doble tocineta',
      'Queso americano',
      'Cebolla Caramelizada',
      'Lechuga',
      'Mostaza',
      'Salsa de la casa',
    ],
    description: 'Doble dosis de sabor para los más hambrientos',
    price: 11.5,
    image: './images/products/burgues_doble.jpg',
  },
]
